#!/bin/bash
set -euo pipefail

eval "$(/opt/homebrew/bin/brew shellenv)"

# JDK 8 casks are Intel-only and need Rosetta 2 on Apple Silicon
if [ "$(uname -m)" = "arm64" ] && ! /usr/bin/pgrep -q oahd; then
  softwareupdate --install-rosetta --agree-to-license || true
fi

brew tap bell-sw/liberica
brew trust bell-sw/liberica

JAVA_CASKS=(
  temurin@8
  temurin@11
  temurin@17
  temurin@21
  temurin@25

  zulu@8
  zulu@11
  zulu@17
  zulu@21
  zulu@25

  corretto@8
  corretto@11
  corretto@17
  corretto@21
  corretto@25

  liberica-jdk8
  liberica-jdk11
  liberica-jdk17
  liberica-jdk21
  liberica-jdk25
)

for cask in "${JAVA_CASKS[@]}"; do
  echo "==> Installing Java cask: $cask"
  brew install --cask "$cask"
done

DOTFILES="${DOTFILES:-$HOME/dotfiles}"
if [[ -f "$(dirname "$0")/java.sh" ]]; then
  DOTFILES="$(cd "$(dirname "$0")/.." && pwd)"
fi
mkdir -p "$DOTFILES/config/zsh"

JAVA_ENV="$DOTFILES/config/zsh/java.zsh"

cat > "$JAVA_ENV" <<'EOF'
# Auto-generated by java.sh

export JAVA8_TEMURIN_HOME="/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home"
export JAVA11_TEMURIN_HOME="/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home"
export JAVA17_TEMURIN_HOME="/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"
export JAVA21_TEMURIN_HOME="/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"
export JAVA25_TEMURIN_HOME="/Library/Java/JavaVirtualMachines/temurin-25.jdk/Contents/Home"

export JAVA8_ZULU_HOME="/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home"
export JAVA11_ZULU_HOME="/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home"
export JAVA17_ZULU_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
export JAVA21_ZULU_HOME="/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home"
export JAVA25_ZULU_HOME="/Library/Java/JavaVirtualMachines/zulu-25.jdk/Contents/Home"

export JAVA8_CORRETTO_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home"
export JAVA11_CORRETTO_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home"
export JAVA17_CORRETTO_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home"
export JAVA21_CORRETTO_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home"
export JAVA25_CORRETTO_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-25.jdk/Contents/Home"

export JAVA8_LIBERICA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-8.jdk/Contents/Home"
export JAVA11_LIBERICA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-11.jdk/Contents/Home"
export JAVA17_LIBERICA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-17.jdk/Contents/Home"
export JAVA21_LIBERICA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-21.jdk/Contents/Home"
export JAVA25_LIBERICA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-25.jdk/Contents/Home"

export JAVA_HOME="$JAVA21_TEMURIN_HOME"
export PATH="$JAVA_HOME/bin:$PATH"

java-use() {
  case "$1" in
    8-temurin) export JAVA_HOME="$JAVA8_TEMURIN_HOME" ;;
    11-temurin) export JAVA_HOME="$JAVA11_TEMURIN_HOME" ;;
    17-temurin) export JAVA_HOME="$JAVA17_TEMURIN_HOME" ;;
    21-temurin) export JAVA_HOME="$JAVA21_TEMURIN_HOME" ;;
    25-temurin) export JAVA_HOME="$JAVA25_TEMURIN_HOME" ;;

    8-zulu) export JAVA_HOME="$JAVA8_ZULU_HOME" ;;
    11-zulu) export JAVA_HOME="$JAVA11_ZULU_HOME" ;;
    17-zulu) export JAVA_HOME="$JAVA17_ZULU_HOME" ;;
    21-zulu) export JAVA_HOME="$JAVA21_ZULU_HOME" ;;
    25-zulu) export JAVA_HOME="$JAVA25_ZULU_HOME" ;;

    8-corretto) export JAVA_HOME="$JAVA8_CORRETTO_HOME" ;;
    11-corretto) export JAVA_HOME="$JAVA11_CORRETTO_HOME" ;;
    17-corretto) export JAVA_HOME="$JAVA17_CORRETTO_HOME" ;;
    21-corretto) export JAVA_HOME="$JAVA21_CORRETTO_HOME" ;;
    25-corretto) export JAVA_HOME="$JAVA25_CORRETTO_HOME" ;;

    8-liberica) export JAVA_HOME="$JAVA8_LIBERICA_HOME" ;;
    11-liberica) export JAVA_HOME="$JAVA11_LIBERICA_HOME" ;;
    17-liberica) export JAVA_HOME="$JAVA17_LIBERICA_HOME" ;;
    21-liberica) export JAVA_HOME="$JAVA21_LIBERICA_HOME" ;;
    25-liberica) export JAVA_HOME="$JAVA25_LIBERICA_HOME" ;;

    *)
      echo "Usage: java-use <version-vendor>"
      echo "Examples:"
      echo "  java-use 21-temurin"
      echo "  java-use 17-corretto"
      echo "  java-use 11-zulu"
      echo "  java-use 8-liberica"
      return 1
      ;;
  esac

  export PATH="$JAVA_HOME/bin:${PATH}"
  java -version
}
EOF

echo
echo "Java env written to:"
echo "$JAVA_ENV"
echo
echo "Installed JDKs:"
/usr/libexec/java_home -V || true
