#!/bin/bash
# macOS Java matrix - Temurin/Zulu/Corretto/Liberica 8-25 + Microsoft 11-25
# Prefer: curl -fsSL .../java-macos.sh -o /tmp/java-macos.sh && bash /tmp/java-macos.sh
# (Needs a real TTY for sudo .pkg password prompts. curl|bash blocks password entry.)
set -uo pipefail

if [ ! -t 0 ]; then
  echo "Don't pipe this script into bash (curl | bash)."
  echo "JDK casks use .pkg installers and need your macOS password via sudo."
  echo "When stdin is the script pipe, sudo can't prompt and it looks stuck."
  echo
  echo "Run instead:"
  echo "  curl -fsSL https://raw.githubusercontent.com/petrademia/dotfiles/main/bootstrap/java-macos.sh -o /tmp/java-macos.sh"
  echo "  bash /tmp/java-macos.sh"
  exit 1
fi

eval "$(/opt/homebrew/bin/brew shellenv)"
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ENV_HINTS=1

# JDK 8 Intel-only casks need Rosetta on Apple Silicon
if [ "$(uname -m)" = "arm64" ] && ! /usr/bin/pgrep -q oahd; then
  softwareupdate --install-rosetta --agree-to-license || true
fi

brew tap bell-sw/liberica
brew trust bell-sw/liberica

# Fully qualified - Liberica is NOT in homebrew/cask core (short name fails if tap missing)
JAVA_CASKS=(
  temurin@8 temurin@11 temurin@17 temurin@21 temurin@25
  zulu@8 zulu@11 zulu@17 zulu@21 zulu@25
  corretto@8 corretto@11 corretto@17 corretto@21 corretto@25
  bell-sw/liberica/liberica-jdk8
  bell-sw/liberica/liberica-jdk11
  bell-sw/liberica/liberica-jdk17
  bell-sw/liberica/liberica-jdk21
  bell-sw/liberica/liberica-jdk25
  microsoft-openjdk@11 microsoft-openjdk@17 microsoft-openjdk@21 microsoft-openjdk@25
)

ok=0 skip=0 fail=0
echo "Note: Microsoft JDKs use .pkg installers and may prompt for your macOS password."
echo

for cask in "${JAVA_CASKS[@]}"; do
  if brew list --cask "$cask" >/dev/null 2>&1; then
    echo "==> skip $cask (already installed)"
    skip=$((skip + 1))
    continue
  fi
  echo "==> Installing Java cask: $cask"
  if brew install --cask "$cask"; then
    ok=$((ok + 1))
  else
    echo "==> FAILED $cask (continuing)"
    fail=$((fail + 1))
  fi
done

DOTFILES="${DOTFILES:-$HOME/dotfiles}"
# When run as a file (not curl|bash), resolve repo root from script location
if [ -n "${BASH_SOURCE[0]:-}" ] && [ -f "${BASH_SOURCE[0]}" ]; then
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  if [ -f "$script_dir/java-macos.sh" ]; then
    DOTFILES="$(cd "$script_dir/.." && pwd)"
  fi
fi
mkdir -p "$DOTFILES/config/zsh"

JAVA_ENV="$DOTFILES/config/zsh/java.zsh"

cat > "$JAVA_ENV" <<'EOF'
# Auto-generated by java-macos.sh

export JAVA8_TEMURIN_HOME="/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home"
export JAVA11_TEMURIN_HOME="/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home"
export JAVA17_TEMURIN_HOME="/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"
export JAVA21_TEMURIN_HOME="/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"
export JAVA25_TEMURIN_HOME="/Library/Java/JavaVirtualMachines/temurin-25.jdk/Contents/Home"

export JAVA8_ZULU_HOME="/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home"
export JAVA11_ZULU_HOME="/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home"
export JAVA17_ZULU_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
export JAVA21_ZULU_HOME="/Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home"
export JAVA25_ZULU_HOME="/Library/Java/JavaVirtualMachines/zulu-25.jdk/Contents/Home"

export JAVA8_CORRETTO_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home"
export JAVA11_CORRETTO_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home"
export JAVA17_CORRETTO_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home"
export JAVA21_CORRETTO_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-21.jdk/Contents/Home"
export JAVA25_CORRETTO_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-25.jdk/Contents/Home"

export JAVA8_LIBERICA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-8.jdk/Contents/Home"
export JAVA11_LIBERICA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-11.jdk/Contents/Home"
export JAVA17_LIBERICA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-17.jdk/Contents/Home"
export JAVA21_LIBERICA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-21.jdk/Contents/Home"
export JAVA25_LIBERICA_HOME="/Library/Java/JavaVirtualMachines/liberica-jdk-25.jdk/Contents/Home"

export JAVA11_MICROSOFT_HOME="/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home"
export JAVA17_MICROSOFT_HOME="/Library/Java/JavaVirtualMachines/microsoft-17.jdk/Contents/Home"
export JAVA21_MICROSOFT_HOME="/Library/Java/JavaVirtualMachines/microsoft-21.jdk/Contents/Home"
export JAVA25_MICROSOFT_HOME="/Library/Java/JavaVirtualMachines/microsoft-25.jdk/Contents/Home"

export JAVA_HOME="$JAVA21_TEMURIN_HOME"
export PATH="$JAVA_HOME/bin:$PATH"

java-use() {
  case "$1" in
    8-temurin) export JAVA_HOME="$JAVA8_TEMURIN_HOME" ;;
    11-temurin) export JAVA_HOME="$JAVA11_TEMURIN_HOME" ;;
    17-temurin) export JAVA_HOME="$JAVA17_TEMURIN_HOME" ;;
    21-temurin) export JAVA_HOME="$JAVA21_TEMURIN_HOME" ;;
    25-temurin) export JAVA_HOME="$JAVA25_TEMURIN_HOME" ;;

    8-zulu) export JAVA_HOME="$JAVA8_ZULU_HOME" ;;
    11-zulu) export JAVA_HOME="$JAVA11_ZULU_HOME" ;;
    17-zulu) export JAVA_HOME="$JAVA17_ZULU_HOME" ;;
    21-zulu) export JAVA_HOME="$JAVA21_ZULU_HOME" ;;
    25-zulu) export JAVA_HOME="$JAVA25_ZULU_HOME" ;;

    8-corretto) export JAVA_HOME="$JAVA8_CORRETTO_HOME" ;;
    11-corretto) export JAVA_HOME="$JAVA11_CORRETTO_HOME" ;;
    17-corretto) export JAVA_HOME="$JAVA17_CORRETTO_HOME" ;;
    21-corretto) export JAVA_HOME="$JAVA21_CORRETTO_HOME" ;;
    25-corretto) export JAVA_HOME="$JAVA25_CORRETTO_HOME" ;;

    8-liberica) export JAVA_HOME="$JAVA8_LIBERICA_HOME" ;;
    11-liberica) export JAVA_HOME="$JAVA11_LIBERICA_HOME" ;;
    17-liberica) export JAVA_HOME="$JAVA17_LIBERICA_HOME" ;;
    21-liberica) export JAVA_HOME="$JAVA21_LIBERICA_HOME" ;;
    25-liberica) export JAVA_HOME="$JAVA25_LIBERICA_HOME" ;;

    11-microsoft) export JAVA_HOME="$JAVA11_MICROSOFT_HOME" ;;
    17-microsoft) export JAVA_HOME="$JAVA17_MICROSOFT_HOME" ;;
    21-microsoft) export JAVA_HOME="$JAVA21_MICROSOFT_HOME" ;;
    25-microsoft) export JAVA_HOME="$JAVA25_MICROSOFT_HOME" ;;

    *)
      echo "Usage: java-use <version-vendor>"
      echo "Vendors: temurin, zulu, corretto, liberica (8/11/17/21/25); microsoft (11/17/21/25)"
      echo "Examples: java-use 21-temurin | java-use 17-corretto | java-use 21-microsoft"
      return 1
      ;;
  esac

  export PATH="$JAVA_HOME/bin:${PATH}"
  java -version
}
EOF

echo
echo "Done. installed=$ok skipped=$skip failed=$fail"
echo "Java env written to: $JAVA_ENV"
echo
echo "Installed JVMs:"
/usr/libexec/java_home -V 2>&1 || true
echo
echo "Switch: java-use 21-temurin"
